name: Verify formatting

on:
  push:
    branches: main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Verify Python formatting
    steps:
    - uses: actions/checkout@v6

    - uses: astral-sh/ruff-action@v3
      with:
        version: "0.12.0"
        args: "format --check"

  djlint:
    runs-on: ubuntu-latest
    name: Check HTML formatting
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install djlint

    - name: Format HTML
      run: djlint . --check
