name: Verify formatting

on:
  push:
    branches: main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Verify Python formatting
    steps:
    - uses: actions/checkout@v6

    - uses: astral-sh/ruff-action@v3
      with:
        version: "0.14.13"
        args: "format --check"

  djlint:
    runs-on: ubuntu-latest
    name: Check HTML formatting
    steps:
    - uses: actions/checkout@v6

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Format HTML
      run: |
        uvx djlint --version
        uvx djlint . --check --configuration pyproject.toml
